/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{vue,js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'inverse-primary': '#b8c4ff',
        primary: '#00288e',
        'on-secondary-fixed-variant': '#005236',
        'on-error': '#ffffff',
        error: '#ba1a1a',
        'surface-bright': '#f8f9ff',
        'surface-container': '#e6eeff',
        'tertiary-container': '#484c4e',
        'outline-variant': '#c4c5d5',
        'surface-dim': '#ccdbf3',
        'tertiary-fixed-dim': '#c4c7c9',
        'surface-tint': '#3755c3',
        'primary-container': '#1e40af',
        'surface-container-low': '#eff4ff',
        'on-primary': '#ffffff',
        surface: '#f8f9ff',
        'tertiary-fixed': '#e0e3e5',
        'on-primary-container': '#a8b8ff',
        'on-secondary-fixed': '#002113',
        'surface-container-high': '#dce9ff',
        'on-error-container': '#93000a',
        'inverse-surface': '#233144',
        'on-primary-fixed-variant': '#173bab',
        'on-secondary': '#ffffff',
        'surface-container-lowest': '#ffffff',
        'on-tertiary-fixed-variant': '#444749',
        'on-surface': '#0d1c2e',
        'on-tertiary-fixed': '#191c1e',
        'primary-fixed-dim': '#b8c4ff',
        'on-surface-variant': '#444653',
        outline: '#757684',
        'error-container': '#ffdad6',
        'surface-variant': '#d5e3fc',
        'surface-container-highest': '#d5e3fc',
        'primary-fixed': '#dde1ff',
        'secondary-fixed': '#6ffbbe',
        tertiary: '#323537',
        'on-tertiary': '#ffffff',
        background: '#f8f9ff',
        'on-primary-fixed': '#001453',
        secondary: '#006c49',
        'secondary-fixed-dim': '#4edea3',
        'on-tertiary-container': '#b9bcbe',
        'on-background': '#0d1c2e',
        'on-secondary-container': '#00714d',
        'secondary-container': '#6cf8bb',
        'inverse-on-surface': '#eaf1ff',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.8px',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        unit: '4px',
        'container-max-width': '1440px',
        gutter: '24px',
        'margin-tablet': '24px',
        'margin-mobile': '16px',
        'margin-desktop': '40px',
      },
      fontFamily: {
        'title-lg': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'headline-md': ['Inter', 'sans-serif'],
        'label-md': ['Inter', 'sans-serif'],
        'headline-lg': ['Inter', 'sans-serif'],
        'title-md': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'title-lg': ['1.25rem', { lineHeight: '1.75rem', fontWeight: '600' }],
        'headline-md': ['1.875rem', { lineHeight: '2.25rem', fontWeight: '600' }],
        'body-md': ['0.875rem', { lineHeight: '1.25rem' }],
        'label-md': ['0.75rem', { lineHeight: '1rem' }],
        'headline-lg': ['2.25rem', { lineHeight: '2.5rem', fontWeight: '600' }],
        'title-md': ['0.875rem', { lineHeight: '1.25rem', fontWeight: '500' }],
        'body-lg': ['1rem', { lineHeight: '1.5rem' }],
      },
    },
  },
  plugins: [],
}