// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PaymentReportService.API.Data;

#nullable disable

namespace PaymentReportService.API.Migrations
{
    [DbContext(typeof(PaymentDbContext))]
    [Migration("20260620013552_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PaymentReportService.API.Models.DebtRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LatestInvoiceId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalPaid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LatestInvoiceId");

                    b.HasIndex("UserId");

                    b.ToTable("DebtRecords");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseId = 1,
                            CourseName = "Tiếng Anh Giao Tiếp A1",
                            DueDate = new DateTime(2024, 2, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            LatestInvoiceId = 1,
                            Status = "DaThanhToan",
                            StudentId = 1,
                            StudentName = "Trần Thị B",
                            TotalAmount = 3000000m,
                            TotalPaid = 3000000m,
                            UpdatedAt = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 3
                        },
                        new
                        {
                            Id = 2,
                            CourseId = 2,
                            CourseName = "Tin học văn phòng",
                            DueDate = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LatestInvoiceId = 2,
                            Status = "ConNo",
                            StudentId = 2,
                            StudentName = "Lê Văn C",
                            TotalAmount = 2500000m,
                            TotalPaid = 1000000m,
                            UpdatedAt = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 3
                        });
                });

            modelBuilder.Entity("PaymentReportService.API.Models.PaymentInvoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PaidAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("PaidDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("PaymentInvoices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClassId = 1,
                            CourseId = 1,
                            CourseName = "Tiếng Anh Giao Tiếp A1",
                            CreatedByUserId = 1,
                            InvoiceDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Note = "Đã thanh toán đủ",
                            PaidAmount = 3000000m,
                            PaidDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            PaymentMethod = "ChuyenKhoan",
                            Status = "DaThanhToan",
                            StudentId = 1,
                            StudentName = "Trần Thị B",
                            TotalAmount = 3000000m
                        },
                        new
                        {
                            Id = 2,
                            ClassId = 2,
                            CourseId = 2,
                            CourseName = "Tin học văn phòng",
                            CreatedByUserId = 1,
                            InvoiceDate = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Note = "Còn nợ 1.500.000đ",
                            PaidAmount = 1000000m,
                            PaidDate = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PaymentMethod = "TienMat",
                            Status = "ThanhToanMotPhan",
                            StudentId = 2,
                            StudentName = "Lê Văn C",
                            TotalAmount = 2500000m
                        });
                });

            modelBuilder.Entity("PaymentReportService.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@trungtam.edu.vn",
                            FullName = "Quản trị viên",
                            IsActive = true,
                            PasswordHash = "$2a$11$AktP7r048dlnRp3jr1eeE.9rNTfdbmzT5Tf8zQ7xJjYkw07wYWWd.",
                            Role = "Admin",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "giaovien01@trungtam.edu.vn",
                            FullName = "Nguyễn Văn A",
                            IsActive = true,
                            PasswordHash = "$2a$11$AktP7r048dlnRp3jr1eeE.9rNTfdbmzT5Tf8zQ7xJjYkw07wYWWd.",
                            Role = "GiaoVien",
                            Username = "giaovien01"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "hocvien01@trungtam.edu.vn",
                            FullName = "Trần Thị B",
                            IsActive = true,
                            PasswordHash = "$2a$11$AktP7r048dlnRp3jr1eeE.9rNTfdbmzT5Tf8zQ7xJjYkw07wYWWd.",
                            Role = "HocVien",
                            Username = "hocvien01"
                        });
                });

            modelBuilder.Entity("PaymentReportService.API.Models.DebtRecord", b =>
                {
                    b.HasOne("PaymentReportService.API.Models.PaymentInvoice", "LatestInvoice")
                        .WithMany("DebtRecords")
                        .HasForeignKey("LatestInvoiceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PaymentReportService.API.Models.User", "User")
                        .WithMany("DebtRecords")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LatestInvoice");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PaymentReportService.API.Models.PaymentInvoice", b =>
                {
                    b.HasOne("PaymentReportService.API.Models.User", "CreatedByUser")
                        .WithMany("Invoices")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("PaymentReportService.API.Models.PaymentInvoice", b =>
                {
                    b.Navigation("DebtRecords");
                });

            modelBuilder.Entity("PaymentReportService.API.Models.User", b =>
                {
                    b.Navigation("DebtRecords");

                    b.Navigation("Invoices");
                });
#pragma warning restore 612, 618
        }
    }
}
