// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentAttendanceService.Data;

#nullable disable

namespace StudentAttendanceService.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260621171101_AddSpecializationToCourse")]
    partial class AddSpecializationToCourse
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StudentAttendanceService.Models.Announcement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TargetRole")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Announcements");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Phòng Đào tạo",
                            Content = "Lịch thi cuối kỳ học kỳ Fall 2024 đã được công bố...",
                            Date = new DateTime(2026, 6, 16, 17, 11, 1, 519, DateTimeKind.Utc).AddTicks(465),
                            Priority = "high",
                            TargetRole = "ALL",
                            Title = "Thông báo lịch thi cuối kỳ"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Phòng Đào tạo",
                            Content = "Thời gian đăng ký học phần bắt đầu từ ngày 15/12/2024...",
                            Date = new DateTime(2026, 6, 13, 17, 11, 1, 519, DateTimeKind.Utc).AddTicks(470),
                            Priority = "medium",
                            TargetRole = "STUDENT",
                            Title = "Đăng ký học phần học kỳ Spring 2025"
                        });
                });

            modelBuilder.Entity("StudentAttendanceService.Models.Attendance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CheckInTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CheckOutTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("Week")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("StudentId");

                    b.ToTable("Attendances");
                });

            modelBuilder.Entity("StudentAttendanceService.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Credits")
                        .HasColumnType("int");

                    b.Property<string>("Faculty")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("LecturerId")
                        .HasColumnType("int");

                    b.Property<int>("MaxStudents")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Room")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Schedule")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Semester")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("SpecializationId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("LecturerId");

                    b.HasIndex("SpecializationId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "CS101",
                            CreatedAt = new DateTime(2026, 6, 21, 17, 11, 1, 519, DateTimeKind.Utc).AddTicks(412),
                            Credits = 3,
                            Faculty = "CNTT",
                            LecturerId = 1,
                            MaxStudents = 60,
                            Name = "Nhập môn lập trình",
                            Room = "A101",
                            Schedule = "Thứ 2, 13:30-16:30",
                            Semester = "Fall 2024",
                            SpecializationId = 1
                        },
                        new
                        {
                            Id = 2,
                            Code = "CS201",
                            CreatedAt = new DateTime(2026, 6, 21, 17, 11, 1, 519, DateTimeKind.Utc).AddTicks(417),
                            Credits = 4,
                            Faculty = "CNTT",
                            LecturerId = 1,
                            MaxStudents = 60,
                            Name = "Cấu trúc dữ liệu",
                            Room = "B202",
                            Schedule = "Thứ 3, 08:00-11:00",
                            Semester = "Fall 2024",
                            SpecializationId = 1
                        },
                        new
                        {
                            Id = 3,
                            Code = "CS301",
                            CreatedAt = new DateTime(2026, 6, 21, 17, 11, 1, 519, DateTimeKind.Utc).AddTicks(419),
                            Credits = 3,
                            Faculty = "CNTT",
                            LecturerId = 2,
                            MaxStudents = 60,
                            Name = "Cơ sở dữ liệu",
                            Room = "C303",
                            Schedule = "Thứ 4, 13:30-16:30",
                            Semester = "Fall 2024",
                            SpecializationId = 2
                        });
                });

            modelBuilder.Entity("StudentAttendanceService.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Head")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("LecturerCount")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("StudentCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "CNTT",
                            CreatedAt = new DateTime(2026, 6, 21, 17, 11, 1, 519, DateTimeKind.Utc).AddTicks(340),
                            Head = "PGS.TS Trần Văn X",
                            LecturerCount = 35,
                            Name = "Công nghệ thông tin",
                            StudentCount = 486
                        },
                        new
                        {
                            Id = 2,
                            Code = "QTKD",
                            CreatedAt = new DateTime(2026, 6, 21, 17, 11, 1, 519, DateTimeKind.Utc).AddTicks(343),
                            Head = "TS. Nguyễn Thị Y",
                            LecturerCount = 28,
                            Name = "Quản trị kinh doanh",
                            StudentCount = 325
                        },
                        new
                        {
                            Id = 3,
                            Code = "NNKT",
                            CreatedAt = new DateTime(2026, 6, 21, 17, 11, 1, 519, DateTimeKind.Utc).AddTicks(345),
                            Head = "ThS. Lê Văn Z",
                            LecturerCount = 20,
                            Name = "Ngôn ngữ Anh",
                            StudentCount = 218
                        });
                });

            modelBuilder.Entity("StudentAttendanceService.Models.Enrollment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EnrollmentDate")
                        .HasColumnType("datetime2");

                    b.Property<double?>("FinalGrade")
                        .HasColumnType("float");

                    b.Property<string>("LetterGrade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("StudentId");

                    b.ToTable("Enrollments");
                });

            modelBuilder.Entity("StudentAttendanceService.Models.LearningResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EnrollmentId")
                        .HasColumnType("int");

                    b.Property<string>("ExamType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Grade")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<double?>("MaxScore")
                        .HasColumnType("float");

                    b.Property<DateTime>("RecordedDate")
                        .HasColumnType("datetime2");

                    b.Property<double?>("Score")
                        .HasColumnType("float");

                    b.Property<double?>("Weight")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("EnrollmentId");

                    b.ToTable("LearningResults");
                });

            modelBuilder.Entity("StudentAttendanceService.Models.Lecturer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Faculty")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("LecturerId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Specialization")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Lecturers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 6, 21, 17, 11, 1, 519, DateTimeKind.Utc).AddTicks(389),
                            Email = "tranvanx@university.edu.vn",
                            Faculty = "CNTT",
                            FullName = "PGS.TS Trần Văn X",
                            LecturerId = "GV001",
                            Phone = "0912345678",
                            Specialization = "Khoa học máy tính",
                            Status = "Active",
                            Title = "Phó Giáo sư"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 6, 21, 17, 11, 1, 519, DateTimeKind.Utc).AddTicks(394),
                            Email = "nguyenthiy@university.edu.vn",
                            Faculty = "QTKD",
                            FullName = "TS. Nguyễn Thị Y",
                            LecturerId = "GV002",
                            Phone = "0912345679",
                            Specialization = "Quản trị chiến lược",
                            Status = "Active",
                            Title = "Tiến sĩ"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 6, 21, 17, 11, 1, 519, DateTimeKind.Utc).AddTicks(396),
                            Email = "levanz@university.edu.vn",
                            Faculty = "NNKT",
                            FullName = "ThS. Lê Văn Z",
                            LecturerId = "GV003",
                            Phone = "0912345680",
                            Specialization = "Ngôn ngữ học",
                            Status = "Active",
                            Title = "Thạc sĩ"
                        });
                });

            modelBuilder.Entity("StudentAttendanceService.Models.Specialization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descrt")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("SpecializationName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SpecializationName")
                        .IsUnique();

                    b.ToTable("Specializations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 6, 21, 17, 11, 1, 519, DateTimeKind.Utc).AddTicks(363),
                            Descrt = "Chuyên ngành nghiên cứu và phát triển phần mềm",
                            IsActive = true,
                            SpecializationName = "Khoa học máy tính"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 6, 21, 17, 11, 1, 519, DateTimeKind.Utc).AddTicks(365),
                            Descrt = "Chuyên ngành phát triển ứng dụng và hệ thống",
                            IsActive = true,
                            SpecializationName = "Kỹ thuật phần mềm"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 6, 21, 17, 11, 1, 519, DateTimeKind.Utc).AddTicks(366),
                            Descrt = "Chuyên ngành quản lý và điều hành doanh nghiệp",
                            IsActive = true,
                            SpecializationName = "Quản trị kinh doanh"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 6, 21, 17, 11, 1, 519, DateTimeKind.Utc).AddTicks(368),
                            Descrt = "Chuyên ngành ngôn ngữ và văn hóa Anh",
                            IsActive = true,
                            SpecializationName = "Ngôn ngữ Anh"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 6, 21, 17, 11, 1, 519, DateTimeKind.Utc).AddTicks(369),
                            Descrt = "Chuyên ngành AI và Machine Learning",
                            IsActive = true,
                            SpecializationName = "Trí tuệ nhân tạo"
                        });
                });

            modelBuilder.Entity("StudentAttendanceService.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Class")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Faculty")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Major")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Class = "K63-CLC",
                            CreatedAt = new DateTime(2026, 6, 21, 17, 11, 1, 519, DateTimeKind.Utc).AddTicks(438),
                            Email = "nguyenvana@university.edu.vn",
                            Faculty = "CNTT",
                            FullName = "Nguyễn Văn A",
                            Major = "Khoa học máy tính",
                            Phone = "0901234567",
                            Status = "Active",
                            StudentId = "2021001234",
                            Year = 2021
                        },
                        new
                        {
                            Id = 2,
                            Class = "K63-CLC",
                            CreatedAt = new DateTime(2026, 6, 21, 17, 11, 1, 519, DateTimeKind.Utc).AddTicks(442),
                            Email = "tranthib@university.edu.vn",
                            Faculty = "CNTT",
                            FullName = "Trần Thị B",
                            Major = "Khoa học máy tính",
                            Phone = "0901234568",
                            Status = "Active",
                            StudentId = "2021001235",
                            Year = 2021
                        },
                        new
                        {
                            Id = 3,
                            Class = "K63-QTKD",
                            CreatedAt = new DateTime(2026, 6, 21, 17, 11, 1, 519, DateTimeKind.Utc).AddTicks(444),
                            Email = "levanc@university.edu.vn",
                            Faculty = "QTKD",
                            FullName = "Lê Văn C",
                            Major = "Quản trị kinh doanh",
                            Phone = "0901234569",
                            Status = "Active",
                            StudentId = "2021001236",
                            Year = 2021
                        });
                });

            modelBuilder.Entity("StudentAttendanceService.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Class")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Faculty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LecturerId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Major")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Specialization")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 6, 21, 17, 11, 1, 519, DateTimeKind.Utc).AddTicks(223),
                            Email = "admin@example.com",
                            Faculty = "Phòng Đào tạo",
                            FullName = "Trần Văn Admin",
                            IsActive = true,
                            Password = "admin123",
                            Phone = "0912345678",
                            Role = "ADMIN",
                            Title = "Quản trị viên"
                        });
                });

            modelBuilder.Entity("StudentAttendanceService.Models.Attendance", b =>
                {
                    b.HasOne("StudentAttendanceService.Models.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StudentAttendanceService.Models.Student", "Student")
                        .WithMany("Attendances")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("StudentAttendanceService.Models.Course", b =>
                {
                    b.HasOne("StudentAttendanceService.Models.Lecturer", "Lecturer")
                        .WithMany("Courses")
                        .HasForeignKey("LecturerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StudentAttendanceService.Models.Specialization", "Specialization")
                        .WithMany("Courses")
                        .HasForeignKey("SpecializationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Lecturer");

                    b.Navigation("Specialization");
                });

            modelBuilder.Entity("StudentAttendanceService.Models.Enrollment", b =>
                {
                    b.HasOne("StudentAttendanceService.Models.Course", "Course")
                        .WithMany("Enrollments")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StudentAttendanceService.Models.Student", "Student")
                        .WithMany("Enrollments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("StudentAttendanceService.Models.LearningResult", b =>
                {
                    b.HasOne("StudentAttendanceService.Models.Enrollment", "Enrollment")
                        .WithMany("LearningResults")
                        .HasForeignKey("EnrollmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enrollment");
                });

            modelBuilder.Entity("StudentAttendanceService.Models.Course", b =>
                {
                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("StudentAttendanceService.Models.Enrollment", b =>
                {
                    b.Navigation("LearningResults");
                });

            modelBuilder.Entity("StudentAttendanceService.Models.Lecturer", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("StudentAttendanceService.Models.Specialization", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("StudentAttendanceService.Models.Student", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("Enrollments");
                });
#pragma warning restore 612, 618
        }
    }
}
